DEBUG: false
MONGODB:
  ADDRESS: 'mongoAddress'
  PORT: 27017
  DATABASE: 'mongoBase'
  AUTHENTICATION:
    ENABLED: false
    USERNAME: 'mongoUser'
    PASSWORD: 'mongoPassword'
    DATABASE: 'mongoBase'
ANNOUNCE:
  ENABLED: true
  BUNGEE: true
  FORMAT: '&7[<server_name>] &6<player_display_name> &8» &fCome play &6<server_name> &fby typing &6/server <server_name>'
ROADS:
  MAKE-ROADS: false
  ROAD-MATERIALS:
  - COBBLESTONE
  - GRASS
  - GRAVEL
  - STONE
CHAT-FORMAT:
  ENABLED: true
  FORMAT: '&f<player_display_name> &8» &f<message>'
  SPECTATOR-FORMAT: '&7[Spectator&7] &r<player_display_name> &8» &f<message>'
SERVER-PREMIUM: true
LEADERBOARD-FORMAT: '&6#<pos> &f<name> &8▶ &f<amount>'
PREFIXES:
  GAME: '&8[&6&lIkara&8] '
  BORDER: '&c[&c&lBorder&c] '
WORLDS:
  LOBBY: lobby
  GAME: potsg_map
LOCATIONS:
  LOBBY:
    YAW: -90
    PITCH: 0
BOOLEANS:
  #
  # LOBBY-ENABLED is to toggle if you have BungeeCord or not (To make global announcements before starting the match)
  #
  LOBBY-ENABLED: true
LOBBY-FALLBACK-SERVER: lobby
GAME-CENTER-LOCATION: 0;100;0
DEATH-MATCH:
  FLOOR-MATERIALS:
  - BEDROCK
  - STONE
  WALL-MATERIALS:
    TOP:
    - FENCE
    BEETWEEN:
    - BEDROCK
    - COBBLESTONE
    - STONE
    BOTTOM:
    - BEDROCK
INFORMATIONS:
  WEB: Ikara.gg
  IP: Ikara.gg
  TS: Ikara.gg/Discord
  STORE: store.Ikara.gg
  SERVER: PotSG-001
BORDER:
  START: 500
  SHRINK-UNTIL: 25
  SHRINK-EVERY-SECONDS: 300
  SHRINK-STREAM: 500;250;150;100;50;25
START-BORDER: 500
REBOOT_COMMAND: stop
POINTS:
  PER-KILL: 5
  PER-WIN: 10
MINIMUM-PLAYERS-TO-START-GAME: 2
MAXIMUM-PLAYERS-PER-GAME: 30
AUTO-START-COUNTDOWN-IN-SECONDS: 20
COUNTDOWNS:
  IN-SECONDS:
    START: 15
    PRE-MATCH: 60
    PVP-PROT: 180
    REBOOT: 30
  IN-MINUTES:
    FEASTS-SPAWN: 8
    DEATH-MATCH: 25
